stages:
  - test

test:
  stage: test
  image: node:18.13.0
  variables: development
  cache:
    paths:
      - node_modules
  before_script:
      - npm install
  script:
        - npm run test
  only:
    - gw
