addons:
  chrome: stable
  firefox: latest
  
stages:
  - test

test:
  stage: test
  image: node:18.13.0
  cache:
    paths:
      - node_modules
  before_script:
      - npm install
  script:
      - chmod +x ./gitlab/test-release.sh
      - chmod +x ./gitlab/verify.sh
      - ./gitlab/test-release.sh
      - ./gitlab/verify.sh
  only:
    - gw
