stages:
  - test

test:
  stage: test
  image: node:18.13.0
  cache:
    paths:
      - node_modules
  before_script:
      - npm install
  script:
      - chmod +x ./travis/test-release.sh
      - chmod +x ./travis/verify.sh
  only:
    - gw
